### PR TITLE
feat(rating): make rating page publicly accessible

### PR DESCRIPTION
**Pull request by arilloid**
## How does this PR impact the user?

https://github.com/user-attachments/assets/41f5cb0d-b87a-4852-bbc3-a905fdebe2bb

## Description

Made the rating page accessible to unauthenticated users by moving the link from game screen to the global header, and adding `/rating` and `/api/rating` to the list of public paths.

## Checklist

- [x] my PR is focused and contains one wholistic change
- [x] I have added screenshots or screen recordings to show the changes

### CODE REVIEW

**Comment by arilloid** [comment]
Hello @yurijmikhalevich!

I've made the rating page publicly accessible. Do you have any suggestions regarding the placement of the rating link in the global header?

I was also thinking about displaying the link conditionally depending on the subtitle to avoid showing it on the rating page itself, please let me know what are your thoughts on that

**Comment by arilloid** [comment]
Hello @yurijmikhalevich , 
Also wanted to let you know that I would love to work on #43, once this one gets merged!

**Review by yurijmikhalevich — APPROVED** [review]

**Review by yurijmikhalevich — APPROVED** [review]
@arilloid, the placement is good and it's ok to keep the link in the menu after navigation. Thank you 🙌

**Comment by yurijmikhalevich** [comment]
Can you please comment on #43? Otherwise, GitHub doesn't let me assign it to you 😄

**Pull request merged**
